linters:
  enable:
    - gosec
    - errcheck
    - gosimple
    - bodyclose
    - staticcheck
    - goimports
  disable:
    - ineffassign
    - unused

issues:
  exclude-files:
    - ".+_test.go"
    - ".+_test_.+.go"
