version: '2'

services:

  hydra:
    build:
      context: .
      dockerfile: Dockerfile-demo
    links:
      - postgres:database
    ports:
      - "4444:4444"
      - "4445:4445"
    environment:
      - SYSTEM_SECRET=${SYSTEM_SECRET}
      - CONSENT_URL=http://${DOCKER_IP}:3000
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres?sslmode=disable
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
    restart: unless-stopped

  consent:
    environment:
      - HYDRA_URL=http://hydra:4444
      - HYDRA_CLIENT_ID=admin
      - HYDRA_CLIENT_SECRET=demo-password
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    image: oryam/hydra-idp-react
    links:
      - hydra
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
