name: "OpenID Connect Conformity Tests"

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  oidc-conformity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      - name: Start service
        run: ./test/conformance/start.sh
      - name: Run tests
        run: ./test/conformance/test.sh -v -short -parallel 16
